### ISSUE TITLE
Listing 9.18 Occasionally Fails with UnauthorizedAccessException

### ISSUE THREAD

**Issue by MarkMichaelis** [IntelliTect/EssentialCSharp#120]
Occasionally, listing 9.18 fails with an `System.UnauthorizedAccessException`.  The exception occurs on the last line of the following snippet:
```
string fileName = @"enumtest.txt";
FileInfo file = new FileInfo(fileName);
file.Open(FileMode.OpenOrCreate).Dispose();
```

It isn't clear what is different between when it succeeds and doesn't succeed making it exceptionally problematic to figure out.

Below is the error output from the test:

```
Test Name:	Main_FileAttributes_UseFlagsAttribute 
Test FullName:	Chapter09.Tests.AddisonWesley.Michaelis.EssentialCSharp.Chapter09.Listing09_18.Tests.ProgramTests.Main_FileAttributes_UseFlagsAttribute
Test Source:	C:\Data\EssentialCSharp\YogaX1\1\SCC\src\Chapter09.Tests\Listing09.18.UsingFlagsAttribute.cs : line 11
Test Outcome:	Failed
Test Duration:	0:00:00

Test Name:	Main_FileAttributes_UseFlagsAttribute
Test Outcome:	Failed
Result StackTrace:	
at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.FileInfo.Open(FileMode mode)
   at AddisonWesley.Michaelis.EssentialCSharp.Chapter09.Listing09_18.Program.Main() in C:\Data\EssentialCSharp\YogaX1\1\SCC\src\Chapter09\Listing09.18.UsingFlagsAttribute.cs:line 13
   at IntelliTect.TestTools.Console.ConsoleAssert.Execute(String givenInput, Action action)
   at IntelliTect.TestTools.Console.ConsoleAssert.Execute(String givenInput, String expectedOutput, Action action, Func`3 areEquivalentOperator, Boolean normalizeLineEndings, String equivalentOperatorErrorMessage)
   at IntelliTect.TestTools.Console.ConsoleAssert.Expect(String expected, Action action, Func`3 comparisonOperator, Boolean normalizeLineEndings, String equivalentOperatorErrorMessage)
   at IntelliTect.TestTools.Console.ConsoleAssert.Expect(String expected, Action action, Boolean normalizeLineEndings)
   at AddisonWesley.Michaelis.EssentialCSharp.Chapter09.Listing09_18.Tests.ProgramTests.Main_FileAttributes_UseFlagsAttribute() in C:\Data\EssentialCSharp\YogaX1\1\SCC\src\Chapter09.Tests\Listing09.18.UsingFlagsAttribute.cs:line 19
Result Message:	
Test method AddisonWesley.Michaelis.EssentialCSharp.Chapter09.Listing09_18.Tests.ProgramTests.Main_FileAttributes_UseFlagsAttribute threw exception: 
System.UnauthorizedAccessException: Access to the path 'C:\Data\EssentialCSharp\YogaX1\1\SCC\src\Chapter09.Tests\bin\Debug\netcoreapp3.0\enumtest.txt' is denied.
``

**Comment by BenjaminMichaelis** [comment]
Closing this for now as I haven't seen this issue recently. Can reopen it it becomes an issue again.

**Comment by BenjaminMichaelis** [comment]
Closing this for now as I haven't seen this issue recently and can't repeat after over 400 runs of the tests. 

Reopen if is more information is found.
